# Generated by Django 5.0.1 on 2025-01-09 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_image_alter_aboutme_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='article',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='blog.article'),
            preserve_default=False,
        ),
    ]
