version: '3'

services:
  app:
    build:
      context: ..
      dockerfile: Dockerfile
      target: development
    ports:
      - 8080:8080
    volumes:
      - ..:/app
      - data:/app/venv
    depends_on:
      - selenium
    networks:
      - dev-net
    environment:
      - SELENIUM_REMOTE_URL=http://selenium:4444/wd/hub
      - APP_URL=app:8080
  
  selenium:
    image: selenium/standalone-firefox
    platform: linux/amd64
    ports:
      - 4444:4444
      - 7900:7900
    environment:
      - VNC_NO_PASSWORD=1
    networks:
      - dev-net

networks:
  dev-net:
    driver: bridge

volumes:
  data:
  