name: My Personal Blog

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TESTCONTAINERS_HOST_OVERRIDE: host.docker.internal
      TEST_HOST: host.docker.internal
      TEST_PORT: 8001

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Set up Docker
      uses: docker/setup-docker-action@v4
    - name: Run e2e tests
      run: |
        make e2e
    - name: Run integration tests
      run: |
        make integration
    - name: Run unit tests
      run: |
        make unit
