name: My Personal Blog

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TESTCONTAINERS_HOST_OVERRIDE: host.docker.internal
      TEST_HOST: host.docker.internal
      TEST_PORT: 8001

    steps:
    - uses: actions/checkout@v4
    
    - name: Build test image
      run: |
        docker build \
          --target development \
          -f Dockerfile \
          -t my-blog-test-image .

    - name: Run tests in container
      run: |
        docker run --rm \
          --network host \
          -e TEST_HOST=$TEST_HOST \
          -e TEST_PORT=$TEST_PORT \
          -v ${{ github.workspace }}:/app \
          my-blog-test-image \
          /bin/bash -lc "cd /app && make migrate && make generate-static && make e2e && make integration && make unit"
