name: My Personal Blog

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: python:latest
      ports:
        - 8081:8081
    env:
      TESTCONTAINERS_HOST_OVERRIDE: host.docker.internal
      TEST_HOST: host.docker.internal
      TEST_PORT: 8001

    steps:
    - uses: actions/checkout@v4
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run e2e tests
      run: |
        make e2e
    - name: Run integration tests
      run: |
        make integration
    - name: Run unit tests
      run: |
        make unit
