name: My Personal Blog

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        playwright install-deps
        playwright install 

    - name: Run migration
      run: |
        make migrate

    - name: Collect static files
      run: |
        make generate-static
        
    - name: Run e2e tests
      run: |
        make e2e

    - name: Run integration tests
      run: |
        make integration

    - name: Run unit tests
      run: |
        make unit
