name: My Personal Blog

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: python:3.11-slim-bullseye
      env:
        TESTCONTAINERS_HOST_OVERRIDE: host.docker.internal
        TEST_HOST: host.docker.internal
        TEST_PORT: "8001"
      ports:
        - 8000
        - 8001

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt

    - name: Run migration
      run: |
        python manage.py migrate

    - name: Collect static files
      run: |
        python manage.py collectstatic

    - name: Run e2e tests
      run: |
        python manage.py test blog.tests.e2e.test_main_page

    - name: Run integration tests
      run: |
        python manage.py test blog.tests.integration

    - name: Run unit tests
      run: |
        python manage.py test blog.tests.unit
