name: My Personal Blog

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:24-dind
        ports:
          - 2375:2375
        options: >-
          --name job-dind --privileged --shm-size=2g
    env:
      DOCKER_HOST: tcp://localhost:2375
      DOCKER_TLS_VERIFY: "0"
      TEST_HOST: "host.docker.internal"
      TEST_PORT: "8001"
      TESTCONTAINERS_HOST_OVERRIDE: "host.docker.internal"
      TESTCONTAINERS_RYUK_DISABLED: "false"
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run migration
      run: |
        make migrate
    - name: Collect static files
      run: |
        make generate-static
    - name: Run e2e tests
      run: |
        make e2e
    - name: Run integration tests
      run: |
        make integration
    - name: Run unit tests
      run: |
        make unit
